/******************************************
Treehouse FSJS Techdegree:
project 1 - A Random Quote Generator
******************************************/

// Created an array with 7 quotes including its sources and addition information
let quotes = [
  {
    quote: "It's the possibility of having a dream come true that makes life interesting",
    source: "Paulo Coelho",
    citation: "The Alchemyst",
    tag: "Philosophy"
  },
  {
    quote: "Memories warm you up from the inside. But they also tear you apart",
    source: "Haruki Murakami",
    citation: "Kafka On The Shore",
    year: 2002
  },
  {
    quote: "Nowadays people know the price of everything and the value of nothing",
    source: "Oscar Wilde",
    citation: "The picture of Dorian Grey",
    year: 1890
  },
  {
    quote: "You are your best thing",
    source: "Toni Morrison",
    citation: "Beloved",
    year: 1987
  },
  {
    quote: "It sounds plausible enough tonight, but wait until tomorrow. Wait for the common sense of the morning",
    source: "H.G. Wells",
    citation: "The Time Machine",
    year: 1895
  },
  {
    quote: "It's much better to do good in a way that no one knows anything about it",
    source: "Leo Tolstoy",
    citation: "Anna Karenina",
    year: 1877
  },
  {
    quote: "I know not all that may be coming, but be it what it will, I’ll go to it laughing",
    source: "Herman Melville",
    year: 1851
  },  
];
  
// change quote every 9 seconds

setInterval(printQuote, 9000);


// Created a function to get a random quote from the array 'quotes'
function getRandomQuote () {
  let randomNumber = Math.floor(Math.random() * quotes.length); 
  let randomQuote = quotes[randomNumber]; 
  return randomQuote;
}


// Generated a random colour - 3 GRB numbers
//Source - https://www.w3schools.com/colors/colors_rgb.asp
function getRandomColour () {
  let randomGreen = Math.ceil(Math.random() * 256);
  let randomRed = Math.ceil(Math.random() * 256);
  let randomBlue = Math.ceil(Math.random() * 256);
  let randomColours = randomGreen + ", " + randomRed + ", " + randomBlue;
  return randomColours;
}


// Replace the existing background colour 
// Source - https://www.w3schools.com/jsref/prop_style_backgroundcolor.asp
function changeBackground () {
  document.body.style.backgroundColor = `rgb( ${getRandomColour()} )`;
}


//Created a function that will print a random quote stored in the getRandomQuote function on to the main page and changes the colour of the backgroud at the same time
function printQuote () {
  let storeObject = getRandomQuote(); // stores a random quote generated by the above function
  let htmlString = '<p class="quote">' + storeObject.quote + '</p>';
  htmlString += '<p class="source">' + storeObject.source;
  if (storeObject.citation) {
    htmlString += '<span class="citation">' + storeObject.citation + '</span>';
  };
  if (storeObject.year) {
    htmlString += '<span class="year">' + storeObject.year + '</span>';
  };
  if (storeObject.tag) {
    htmlString += '<span class="tag">, ' + storeObject.tag + '</span>';
  }
  htmlString += '</p>'; 
  document.getElementById('quote-box').innerHTML = htmlString;
  changeBackground();
  return htmlString; 
}



/***
 * click event listener for the print quote button
 * DO NOT CHANGE THE CODE BELOW!!
***/

document.getElementById('load-quote').addEventListener("click", printQuote, false);